# Generated by Django 2.2.1 on 2019-10-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_desprition_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='desprition',
            new_name='description',
        ),
    ]
